image: golang:1.12.4-alpine

stages:
  - build-and-test
  - staging

build-binary:
  stage: build-and-test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - /go/pkg/mod
  before_script:
    - apk add --no-cache ca-certificates git
    - go mod download
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

build-docker-image:
  stage: build-and-test
  image: docker:18.09.5-git
  services:
    - docker:dind
  script:
    - mkdir image
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker save -o image/app.tar $CI_REGISTRY_IMAGE
  artifacts:
    paths:
      - image/

run-unittests:
  stage: build-and-test
  image: circleci/golang:1.12
  script:
    - make unit_ci

run-integration-test:
  stage: build-and-test
  image: circleci/golang:1.12
  variables:
    # When using dind service we need to instruct docker, to talk with the
    # daemon started inside of the service. The daemon is available with
    # a network connection instead of the default /var/run/docker.sock socket.
    #
    # The 'docker' hostname is the alias of the service container as described at
    # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
    #
    # Note that if you're using the Kubernetes executor, the variable should be set to
    # tcp://localhost:2375/ because of how the Kubernetes executor connects services
    # to the job container
    # DOCKER_HOST: tcp://localhost:2375/
    #
    # For non-Kubernetes executors, we use tcp://docker:2375/
    DOCKER_HOST: tcp://docker:2375/
    # When using dind, it's wise to use the overlayfs driver for
    # improved performance.
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - sudo apt install docker-compose
    - make integration_ci


push-docker-image:
  stage: staging
  image: docker:18.09.5-git
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker load -i image/app.tar
    - docker push registry.gitlab.com/gyuhwan/apas-todo-apiserver
  only:
    - master
