image: golang:1.10.3

variables:
  REPO_NAME: gitlab.com/gyuhwan/apas-todo-apiserver

stages:
  - build
  - test

build-project:
  stage: build
  script:
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go get github.com/golang/dep/cmd/dep
    - $GOPATH/bin/dep ensure
    - go build ./...

test-project:
  stage: test
  script:
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go get github.com/golang/dep/cmd/dep
    - $GOPATH/bin/dep ensure
    - go test ./... -cover
  coverage: '/coverage: \d+\.\d+% of statements/'