image: golang:1.11-alpine

stages:
  - test
  - build

before_script:
    - apk add --no-cache ca-certificates git gcc
    - go mod download

build:
  stage: build
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

test:
  stage: test
  script:
    - CGO_ENABLED=0 go test ./...