image: golang:1.11-alpine

stages:
  - test
  - build

before_script:
    - apk add --no-cache ca-certificates git gcc
    - go mod download

build:
  stage: build
  script:
    - go build

test:
  stage: test
  script:
    - go test ./...