version: "2.0"
services:
  redis:
    image: redis:5.0.5-alpine
    command: sh -c 'exec redis-server --requirepass "$REDIS_PASSWORD"'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6378:6379
    networks:
      - internal
  postgres:
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - internal

networks:
  internal:
    driver: bridge
