version: "2.0"
services:
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6378:6379
    networks:
      - internal
  postgres:
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_NAME}
    ports:
      - ${TEST_POSTGRES_PORT}:5432
    networks:
      - internal

networks:
  internal:
    driver: bridge
