definitions:
  api.ErrorMetaData:
    properties:
      message:
        type: string
    type: object
  api.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/api.ErrorMetaData'
        type: object
    type: object
  auth.AccessTokenByRefreshRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  auth.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  auth.TokenResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      type:
        type: string
    type: object
  auth.tokenResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      type:
        type: string
    type: object
  user.UserResponse:
    properties:
      create_at:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  user.createUserRequestDto:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is a apas todo api server.
  license: {}
  title: APAS TODO API
  version: "1.0"
paths:
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      description: Get new access token by refreshtoken
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.AccessTokenByRefreshRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/auth.tokenResponse'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "401":
          description: Invalid credential
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth API
  /api/auth/token:
    post:
      consumes:
      - application/json
      description: Issue new token
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/auth.TokenResponse'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "401":
          description: Invalid credential
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth API
  /api/healthy:
    get:
      description: Get server healthy
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - App API
  /api/users:
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: user payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/user.createUserRequestDto'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/user.UserResponse'
        "400":
          description: Invalid user payload
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "409":
          description: Already exists user
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - User API
  /api/version:
    get:
      description: Get server version
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - App API
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
