definitions:
  api.ErrorMetaData:
    properties:
      message:
        type: string
    type: object
  api.ErrorResponseDTO:
    properties:
      error:
        $ref: '#/definitions/api.ErrorMetaData'
        type: object
    type: object
  auth.accessTokenByRefreshRequestDTO:
    properties:
      token:
        type: string
    type: object
  auth.loginRequestDTO:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  auth.tokenResponseDTO:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      type:
        type: string
    type: object
  todo.addTodoRequestDTO:
    properties:
      contents:
        type: string
      title:
        type: string
    type: object
  todo.todoResponseDTO:
    properties:
      assignor_id:
        type: integer
      contents:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  user.createUserRequestDTO:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  user.userResponseDTO:
    properties:
      created_at:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is a apas todo api server.
  license: {}
  title: APAS TODO API
  version: "1.0"
paths:
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      description: Get new access token by refreshtoken
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.accessTokenByRefreshRequestDTO'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/auth.tokenResponseDTO'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/api.ErrorResponseDTO'
        "401":
          description: Invalid credential
          schema:
            $ref: '#/definitions/api.ErrorResponseDTO'
      tags:
      - Auth API
  /api/auth/token:
    post:
      consumes:
      - application/json
      description: Issue new token
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.loginRequestDTO'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/auth.tokenResponseDTO'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/api.ErrorResponseDTO'
        "401":
          description: Invalid credential
          schema:
            $ref: '#/definitions/api.ErrorResponseDTO'
      tags:
      - Auth API
  /api/healthy:
    get:
      description: Get server healthy
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - App API
  /api/todos:
    get:
      consumes:
      - application/json
      description: Fetch todos of authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/todo.todoResponseDTO'
            type: array
        "404":
          description: User Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponseDTO'
      security:
      - ApiKeyAuth: []
      tags:
      - Todo API
    post:
      consumes:
      - application/json
      description: Add new todo
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/todo.addTodoRequestDTO'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/todo.todoResponseDTO'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/api.ErrorResponseDTO'
      security:
      - ApiKeyAuth: []
      tags:
      - Todo API
  /api/user:
    get:
      consumes:
      - application/json
      description: Fetch user itself by access_token
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/user.userResponseDTO'
        "404":
          description: User Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponseDTO'
      security:
      - ApiKeyAuth: []
      tags:
      - User API
  /api/users:
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: user payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/user.createUserRequestDTO'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/user.userResponseDTO'
        "400":
          description: Invalid user payload
          schema:
            $ref: '#/definitions/api.ErrorResponseDTO'
        "409":
          description: Already exists user
          schema:
            $ref: '#/definitions/api.ErrorResponseDTO'
      tags:
      - User API
  /api/version:
    get:
      description: Get server version
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - App API
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
