on: [push, pull_request]
name: My Workflows
jobs:
  "Build":
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.13.1"

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build ./...
  "Build-Docker-Image":
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: DOCKER_BUILDKIT=1 docker build -t docker.pkg.github.com/gghcode/apas-todo-apiserver/app .

      - name: Export Docker Image
        run: docker save docker.pkg.github.com/gghcode/apas-todo-apiserver/app > image.tar

      - uses: actions/upload-artifact@v1
        with:
          name: docker-image-tar
          path: image.tar
  "Integration-Test":
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.13.1"

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Integration Test
        run: make integration_ci

      - name: Upload codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -F integration ||
            echo 'Codecov failed to upload'
  "Unit-Test":
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.13.1"

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Unit Test
        run: make unit_ci

      - name: Upload codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -F unittests || 
            echo 'Codecov failed to upload'
